### ISSUE TITLE
Cannot Connect to Live or Test Networks

### ISSUE THREAD

**Issue by aldengolab** [hyperledger/indy-client#188]
Saw that there was a closed issue on connection to the test network (#39, see also on [forum](http://forum.sovrin.org/t/pool-transactions-file-not-found-root-sovrin-pool-transactions-sandbox/176/3)), but the suggested methods for resolving seem outdated since the data directory and all the files referenced have been eliminated in #161, https://github.com/sovrin-foundation/sovrin-client/commit/ad40ad148cb0f6a10d513b385782b7492d0c4402 [Edit: these files were moved to [sovrin-common](https://github.com/sovrin-foundation/sovrin-common/tree/master/data), so unclear what the issue is]. Executed `pip install -U --no-cache-dir sovrin-client` to make sure I'm running on the most recently updated version. Any help would be appreciated; let me know if I can provide additional information. Currently operating on Ubuntu Xenial 16.04.2 LTS. 

When entering the command `connect live`, I receive the following response:

`New keyring Default created
Active keyring set to "Default"
Active keyring set to "Default"
Client sovrinPuZy0s initialized with the following node registry:
    Node1C listens at 127.0.0.1 on port 9702
    Node2C listens at 127.0.0.1 on port 9704
    Node3C listens at 127.0.0.1 on port 9706
    Node4C listens at 127.0.0.1 on port 9708
Active client set to sovrinPuZy0s
7mggMedhAzBRztZCzYHFcSB2Pc4Y8DaQpKpukDRXoF4T listening for other nodes at 0.0.0.0:6006
7mggMedhAzBRztZCzYHFcSB2Pc4Y8DaQpKpukDRXoF4T looking for Node3C at 127.0.0.1:9706
7mggMedhAzBRztZCzYHFcSB2Pc4Y8DaQpKpukDRXoF4T looking for Node1C at 127.0.0.1:9702
7mggMedhAzBRztZCzYHFcSB2Pc4Y8DaQpKpukDRXoF4T looking for Node2C at 127.0.0.1:9704
7mggMedhAzBRztZCzYHFcSB2Pc4Y8DaQpKpukDRXoF4T looking for Node4C at 127.0.0.1:9708
Connecting to live...`

But when I check `status`, the client is still connecting:

`Attempting connection to live Sovrin network`

When entering the command `connect test` I get:

`Client sovrintbwPR4 initialized with the following node registry:
    EvernymV1C      listens at 52.33.22.91    on port 9722
    EvernymV2C      listens at 52.38.24.189   on port 9724
    WSECUC          listens at 40.121.149.41  on port 9726
    BIGC            listens at 52.160.103.164 on port 9728
    RespectNetworkC listens at 54.173.9.185   on port 9730
    FCUC            listens at 69.144.146.171 on port 9734
    BYUC            listens at 54.193.6.155   on port 9745
    BULLDOGC        listens at 52.56.74.57    on port 9747
Active client set to sovrintbwPR4
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp listening for other nodes at 0.0.0.0:6010
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for BULLDOGC at 52.56.74.57:9747
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for EvernymV2C at 52.38.24.189:9724
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for RespectNetworkC at 54.173.9.185:9730
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for BIGC at 52.160.103.164:9728
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for FCUC at 69.144.146.171:9734
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for EvernymV1C at 52.33.22.91:9722
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for WSECUC at 40.121.149.41:9726
4BRYKATV8mNki81zV1jEsh8z9iJYeChzcihfytoE3YJp looking for BYUC at 54.193.6.155:9745
Connecting to test...`

With the same attempting `status`: 

`Attempting connection to test Sovrin network`

**Comment by vanhumbeecka** [comment]
Same.

I use the public docker image (sovrinfoundation/sovrin) to boot the whole thing up.
When I try to connect to the 'test' network, only the "EvernymV1C" and "EvernymV2C" are connected. All the other nodes are kept in a state of 'looking for ... at ...'

Running ```status``` is still displaying ```Attempting connection to test Sovrin network```. Probably because not all nodes are connected yet, only a few, which is not enough it seems.

**Comment by dhh1128** [comment]
@vanhumbeecka and @aldengolab: the problem is the list of nodes you are trying to connect to. You need to update your genesis transactions files to the ones published here: https://github.com/sovrin-foundation/sovrin-common/tree/master/data. I believe you will find these same files somewhere under ~/.sovrin on your local machine. You may need to delete some old state files when you drop these new files in. @keenondrums or @AlexanderShekhovcov , can either of you improve my advice?

**Comment by AlexanderShekhovcov** [comment]
For @aldengolab 's case 
```
pip install -U --no-cache-dir sovrin-client
wget -O ~/.sovrin/pool_transactions_sandbox https://raw.githubusercontent.com/sovrin-foundation/sovrin-common/master/data/pool_transactions_sandbox
```
should be enough. 

@dhh1128 For @vanhumbeecka 's case I think we should update our docker image. The image looks quite outdated.
