### ISSUE TITLE
Docker image libpbc.so.1 not found

### ISSUE THREAD

**Issue by dsanchezseco** [hyperledger/indy-client#44]
I cloned the repo and created the docker image using the supplied Dockerfile but when starting a container with the generated image the error 
```Loading module /usr/local/lib/python3.5/dist-packages/config/config-crypto-example1.py
libpbc.so.1: cannot open shared object file: No such file or directory
``` 
is prompted and the container stops

**Comment by dhh1128** [comment]
@AlexanderShekhovcov, who is working on Docker stuff lately?
